### ISSUE TITLE
Don't download this, its a virus

### ISSUE THREAD

**Issue by Viverny** [AngelFireLA/AngelFire-Brawlermaker#8]
It got flagged as **Win64:Evo-gen [Trj]**, **Trojan.Agent.Script.1762566**, and **Trojan.Win32.Save.a** by **4** out of **5** antiviruses, don't use this.

**Comment by AngelFireLA** [comment]
Bro never used GitHub 
You can look at the whole code
You can even build it yourself with pyinstaller
I just made an exe because people struggled to run the python script
Also I don't know where you got this stats because you're one of the first to say that 
It's amazing how someone on GitHub, an open source platform, don't know that you can check yourself 
It's not even a big project, it's one python file with about a thousand lines so you can quickly check yourself 
I realize to build the exe you would need the app.spec script which I can provide and you'll see you can get the exact same file
Really, people like you makes me mad

**Comment by AngelFireLA** [comment]
So idk what antivirus you have or where you checked it
Also another way to check is testing with tria.ge in case you haven't heard of it

**Comment by AngelFireLA** [comment]
Ok I was going to check on virustotao because I thought this could show that it's not a virus, but it's from where you got the results 
Most was from random antivirus but still there was an Avast detection 
Which is weird because it's not even that complex of an app so idk what got detected 
And as I also usually use virus total, I understand 
I'm sorry if I delt angry as your concern seem genuine 
Though it doesn't excuse the things I said above to check

**Comment by AngelFireLA** [comment]
Inactive
